export const bookCategories = [
    "Kurgu",
    "Kurgu Dışı",
    "Gizem",
    "Gerilim",
    "Fantastik",
    "Bilim Kurgu",
    "Romantik",
    "Tarihsel",
    "Biyografi",
    "Otobiyografi",
    "Kişisel Gelişim",
    "Sağlık",
    "Yemek",
    "Sanat",
    "Şiir",
    "Grafik Roman",
    "Genç Yetişkin",
    "Çocuk",
    "Gezi",
    "Bilim",
    "Teknoloji",
    "İş Dünyası",
    "Ekonomi",
    "Felsefe",
    "Psikoloji",
    "Eğitim",
    "Din",
    "Spiritüel",
    "Gerçek Suç",
    "Mizah",
    "Spor",
    "Müzik",
    "El Sanatları & Hobi",
    "Ev & Bahçe",
    "Ebeveynlik",
    "Politika",
    "Doğa",
    "Hayvanlar",
    "Tarih",
    "Antoloji",
    "Klasikler",
    "Drama",
    "Macera",
    "Savaş",
    "Western",
    "Korku",
    "Anı",
    "Deneme",
    "Kısa Öykü",
    "LGBTQ+",
    "Kültürel",
    "Hukuk",
    "Tıp",
    "Medya Uyarlaması",
    "Antropoloji",
    "Mimarlık",
    "Astronomi",
    "Çevre",
    "Fantastik & Büyü",
    "Edebi Kurgu",
    "Kentsel Fantastik",
    "Paranormal",
    "Gerilim",
    "Epik Fantastik",
    "Distopya",
    "Büyüme Hikayesi",
    "Suç",
    "Politik Gerilim",
    "Doğaüstü",
    "Aile Destanı"
];
